# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CoBrA Lab
tagline:          'Computational Brain Anatomy Laboratory at the Douglas Institute'
description:      ''
url:              http://cobralab.ca
baseurl:          /hyde/

author:
  name:           'Gabriel Devenyi'
  url:            https://twitter.com/staticwave_ace

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cobralab

collections:
  members:
      output: true
  software:
      output: true
  atlases:
      output: true
  projects:
      output: true
