# Permalinks
permalink:        pretty

# Setup
title:            CoBrA Lab
tagline:          'Computational Brain Anatomy Laboratory at the Douglas Institute'
description:      'Computational Brain Anatomy Laboratory at the Douglas Institute'
url:              http://cobralab.ca
baseurl:

author:
  name:           'Gabriel Devenyi'
  url:            https://twitter.com/staticwave_ace

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/cobralab

collections:
  staff:
      output: true
  staffpast:
      output: true
  grad:
      output: true
  gradpast:
      output: true
  undergrad:
      output: true
  undergradpast:
      output: true
  postdocs:
      output: true
  postdocspast:
      output: true
  software:
      output: true
  atlases:
      output: true
  projects:
      output: true
  members:
      output: true
